# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Titulo:')),
                ('date', models.DateTimeField(verbose_name='Data de publica\xe7\xe3o:')),
                ('author', models.CharField(max_length=60, verbose_name='Conte\xeddo da p\xe1gina:')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
