# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='url',
            field=models.URLField(default=['datetime', 'timezone'], verbose_name='Url'),
            preserve_default=False,
        ),
    ]
