# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('nasci', models.DateField()),
                ('descr', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
        ),
    ]
